'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace bhattji.Modules.Dispatchs
    Partial Public Class Details
        Protected WithEvents plDispatchCode As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtDispatchCode As System.Web.UI.WebControls.Label
        Protected WithEvents plDispatchName As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtDispatchName As System.Web.UI.WebControls.Label
        Protected WithEvents plEmail As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtEmail As System.Web.UI.WebControls.Label
        Protected WithEvents plOffice As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents lblOffice As System.Web.UI.WebControls.Label
        Protected WithEvents plCommRate As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtCommRate As System.Web.UI.WebControls.Label
        Protected WithEvents plDefDisp As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtDefDisp As System.Web.UI.WebControls.Label
        Protected WithEvents plDispPassw As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtDispPassw As System.Web.UI.WebControls.Label
        Protected WithEvents plStatus As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents imgStatus As System.Web.UI.WebControls.Image
        Protected WithEvents plOffLogNo As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtOffLogNo As System.Web.UI.WebControls.Label
        Protected WithEvents plDOffLogNo As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtDOffLogNo As System.Web.UI.WebControls.Label
        Protected WithEvents plClearCode As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents imgClearCode As System.Web.UI.WebControls.Image
        Protected WithEvents plWhatProcess As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtWhatProcess As System.Web.UI.WebControls.Label
        Protected WithEvents plXMProc As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtXMProc As System.Web.UI.WebControls.Label
        Protected WithEvents plViewOrder As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtViewOrder As System.Web.UI.WebControls.Label
        Protected WithEvents ctlDispatchIOs As DotNetNuke.UI.UserControls.DualListControl
        Protected WithEvents btnUpdateIOs As System.Web.UI.WebControls.Button
        Protected WithEvents divButtons As System.Web.UI.HtmlControls.HtmlGenericControl
        Protected WithEvents tdEdit As System.Web.UI.HtmlControls.HtmlTableCell
        Protected WithEvents hypImgEdit As System.Web.UI.WebControls.HyperLink
        Protected WithEvents hypEdit As System.Web.UI.WebControls.HyperLink
        Protected WithEvents hypImgClose As System.Web.UI.WebControls.HyperLink
        Protected WithEvents hypClose As System.Web.UI.WebControls.HyperLink
        Protected WithEvents hypImgPrint As System.Web.UI.WebControls.HyperLink
        Protected WithEvents hypPrint As System.Web.UI.WebControls.HyperLink
        Protected WithEvents ctlAudit As DotNetNuke.UI.UserControls.ModuleAuditControl
        Protected WithEvents ctlTracking As DotNetNuke.UI.UserControls.URLTrackingControl
        Protected WithEvents plAllowXM As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents chkAllowXM As System.Web.UI.WebControls.CheckBox
        Protected WithEvents plLogonLink As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtLogonLink As System.Web.UI.WebControls.Label
        Protected WithEvents plLogDate As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtLogDate As System.Web.UI.WebControls.Label
        Protected WithEvents cmdCalendarLogDate As System.Web.UI.WebControls.HyperLink
        Protected WithEvents plLogTime As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtLogTime As System.Web.UI.WebControls.Label
        Protected WithEvents Label1 As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents Checkbox1 As System.Web.UI.WebControls.CheckBox
        Protected WithEvents Label2 As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents Label3 As System.Web.UI.WebControls.Label
        Protected WithEvents Label4 As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents Label5 As System.Web.UI.WebControls.Label
        Protected WithEvents Hyperlink1 As System.Web.UI.WebControls.HyperLink
        Protected WithEvents Label6 As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents Label7 As System.Web.UI.WebControls.Label
    End Class
End Namespace
