'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhattji.Modules.Dispatchs

    Partial Public Class EditItem

        '''<summary>
        '''plDispatchCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDispatchCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDispatchCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDispatchCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imbAddUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbAddUser As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''valDispatchCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDispatchCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxDispatchCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxDispatchCode As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plDispPassw control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDispPassw As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDispPassw control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDispPassw As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdUpdatePassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdatePassword As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''valDispPassw control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDispPassw As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxDispPassw control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxDispPassw As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plDispatchName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDispatchName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDispatchName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDispatchName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valDispatchName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDispatchName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxDispatchName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxDispatchName As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmail As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''valEmail1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmail1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxEmail As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''valEmail0 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmail0 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''vlxEmail0 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxEmail0 As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plOffice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOffice As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlOfficeOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlOfficeOwner As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''valddlOfficeOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valddlOfficeOwner As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxddlOfficeOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxddlOfficeOwner As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plOfficeOverride control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOfficeOverride As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtOfficeOverride control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOfficeOverride As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''fteOfficeOverride control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fteOfficeOverride As Global.AjaxControlToolkit.FilteredTextBoxExtender

        '''<summary>
        '''cvOfficeOverride control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvOfficeOverride As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''vlxOfficeOverride control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxOfficeOverride As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plManagerOverride control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plManagerOverride As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlManagerOverride control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlManagerOverride As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''valManagerOverride control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valManagerOverride As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxManagerOverride control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxManagerOverride As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plCommRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCommRate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCommRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCommRate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''fteCommRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fteCommRate As Global.AjaxControlToolkit.FilteredTextBoxExtender

        '''<summary>
        '''trStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trStatus As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStatus As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plDefDisp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDefDisp As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDefDisp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDefDisp As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plOffLogNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOffLogNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtOffLogNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOffLogNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plDOffLogNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDOffLogNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDOffLogNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDOffLogNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plClearCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plClearCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkClearCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkClearCode As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plWhatProcess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plWhatProcess As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtWhatProcess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWhatProcess As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plXMProc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plXMProc As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtXMProc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtXMProc As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plViewOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plViewOrder As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtViewOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtViewOrder As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tblJrcOffices control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblJrcOffices As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''ctlDispatchIOs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlDispatchIOs As Global.DotNetNuke.UI.UserControls.DualListControl

        '''<summary>
        '''btnUpdateIOs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateIOs As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''tblUserRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblUserRoles As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''ddlPortals control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPortals As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnRoles As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''tdUserAndRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdUserAndRoles As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''cblUserAndRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cblUserAndRoles As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cmdAddUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddUser As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''chkSelectAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSelectAll As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''btnUpdateRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateRoles As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''divPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPopup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''imbUpdateUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbUpdateUser As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdUpdateUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdateUser As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''valValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''trUpdateRedirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trUpdateRedirection As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ddlUpdateRedirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlUpdateRedirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdAdd As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imbAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbAdd As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdUpdate As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imbUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbUpdate As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbCancel As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdDelete As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imbDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbDelete As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdPrint As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''hypImgPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypImgPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''ctlAudit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAudit As Global.DotNetNuke.UI.UserControls.ModuleAuditControl

        '''<summary>
        '''ctlTracking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTracking As Global.DotNetNuke.UI.UserControls.URLTrackingControl

        '''<summary>
        '''plAllowXM control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAllowXM As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowXM control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowXM As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plLogonLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLogonLink As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLogonLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLogonLink As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plLogDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLogDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLogDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLogDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalendarLogDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalendarLogDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''plLogTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLogTime As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLogTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLogTime As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
