'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhattji.Modules.SalesPersons

    Partial Public Class Details

        '''<summary>
        '''plDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDriverCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDriverCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plDriverName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDriverName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDriverName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDriverName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plOfficeOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOfficeOwner As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlOfficeOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlOfficeOwner As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plDLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDLastName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plDFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDFirstName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDLastName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtDFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDFirstName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plAddressLine1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddressLine1 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAddressLine1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddressLine1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAddressLine2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddressLine2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCity As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtZipCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCountryCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCountryCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCountryCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCountryCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plPhoneNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPhoneNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPhoneNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhoneNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plExt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plExt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtExt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plFaxNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFaxNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtFaxNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFaxNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCellPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCellPhone As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plPager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPager As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCellPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCellPhone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPager As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailAddress As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plLastLoadID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastLoadID As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plLastLoad control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastLoad As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastLoadID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastLoadID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtLastLoad control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastLoad As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plLastLoadDeliv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastLoadDeliv As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastLoadDeliv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastLoadDeliv As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plLastPU control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastPU As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plLastDP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastDP As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastPU control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastPU As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtLastDP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastDP As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plLastTrailerUsed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastTrailerUsed As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastTrailerUsed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastTrailerUsed As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plAccountNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAccountNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAccountNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAccountNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCommRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCommRate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCommRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCommRate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCalc85 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCalc85 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''imgCalc85 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgCalc85 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''plDvrDedPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDvrDedPct As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDvrDedPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDvrDedPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plDvrDedResn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDvrDedResn As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDvrDedResn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDvrDedResn As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plJRCTrailer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plJRCTrailer As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtJRCTrailer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtJRCTrailer As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plDriverNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDriverNotes As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDriverNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDriverNotes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plAdminExempt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAdminExempt As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''imgAdminExempt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAdminExempt As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''plStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''imgStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgStatus As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''plBrokerCodeD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBrokerCodeD As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtBrokerCodeD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBrokerCodeD As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plDrugDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDrugDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plTruckInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTruckInsDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDrugDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDrugDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTruckInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTruckInsDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plLicenceDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLicenceDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plTrailerInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTrailerInsDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLicenceDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLicenceDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTrailerInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTrailerInsDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plRegRenewDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRegRenewDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plNewLeaseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNewLeaseDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRegRenewDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRegRenewDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtNewLeaseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNewLeaseDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plMedicalDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMedicalDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plLogBookOS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLogBookOS As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtMedicalDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMedicalDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''imgLogBookOS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgLogBookOS As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lbxSalesPersonIOs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbxSalesPersonIOs As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''ctlSalesPersonIOs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlSalesPersonIOs As Global.DotNetNuke.UI.UserControls.DualListControl

        '''<summary>
        '''btnUpdateIOs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateIOs As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''divButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdEdit As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''hypImgEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypImgEdit As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypEdit As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypImgClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypImgClose As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypClose As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypImgPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypImgPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''ctlAudit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAudit As Global.DotNetNuke.UI.UserControls.ModuleAuditControl

        '''<summary>
        '''ctlTracking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTracking As Global.DotNetNuke.UI.UserControls.URLTrackingControl

        '''<summary>
        '''plAddressLine2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddressLine2 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plAddressLine3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddressLine3 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAddressLine3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddressLine3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plState As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plZipCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plLoadType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLoadType As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLoadType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLoadType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plSafetyAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSafetyAuth As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSafetyAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSafetyAuth As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plSafetyNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSafetyNotes As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSafetyNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSafetyNotes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCalc87 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCalc87 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCalc87 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCalc87 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plViewOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plViewOrder As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtViewOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtViewOrder As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
