'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhattji.Modules.SalesPersons

    Partial Public Class EditItem

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''valValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''trUpdateRedirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trUpdateRedirection As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ddlUpdateRedirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlUpdateRedirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdAdd As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imbAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbAdd As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdUpdate As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imbUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbUpdate As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbCancel As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdDelete As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imbDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbDelete As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdPrint As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''hypImgPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypImgPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblDriverTerminated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDriverTerminated As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trNormal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trNormal As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDriverCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plDriverName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDriverName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plOfficeOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOfficeOwner As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plSafetyAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSafetyAuth As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDriverCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDriverCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxDriverCode As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''cvDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvDriverCode As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''vlxDriverCode0 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxDriverCode0 As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''actDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents actDriverCode As Global.AjaxControlToolkit.FilteredTextBoxExtender

        '''<summary>
        '''txtDriverName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDriverName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlOfficeOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlOfficeOwner As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''valddlOfficeOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valddlOfficeOwner As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxddlOfficeOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxddlOfficeOwner As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''imgActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgActive As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''chkStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStatus As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''imgStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgStatus As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''chkSafetyAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSafetyAuth As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''imgSafetyAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgSafetyAuth As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''plDLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDLastName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valDLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDLastName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxDLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxDLastName As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plDFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDFirstName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valDFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxDFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxDFirstName As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plAddressLine1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddressLine1 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAddressLine1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddressLine1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAddressLine2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddressLine2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCity As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlStateCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStateCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtZipCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valState As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plCountryCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCountryCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCountryCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCountryCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plAccountNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAccountNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAccountNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAccountNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valAccountNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAccountNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxAccountNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxAccountNo As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''cvAccountNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvAccountNo As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''vlxAccountNo0 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxAccountNo0 As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plPhoneNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPhoneNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPhoneNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhoneNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plExt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plExt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtExt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExt As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''meePhoneNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents meePhoneNo As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''plFaxNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFaxNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtFaxNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFaxNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''meeFaxNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents meeFaxNo As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''plCellPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCellPhone As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCellPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCellPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''meeCellPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents meeCellPhone As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''plPager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPager As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPager As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''meePager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents meePager As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''plEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailAddress As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmailAddress As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''plSafetyNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSafetyNotes As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSafetyNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSafetyNotes As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tdLastLoadID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdLastLoadID As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''plLastLoadID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastLoadID As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastLoadID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastLoadID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plLastLoad control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastLoad As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastLoad control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastLoad As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plLastLoadDeliv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastLoadDeliv As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastLoadDeliv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastLoadDeliv As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plLastTrailerUsed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastTrailerUsed As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastTrailerUsed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastTrailerUsed As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plLastPU control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastPU As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastPU control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastPU As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plLastDP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastDP As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastDP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastDP As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCommRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCommRate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCommRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCommRate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valCommRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCommRate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxCommRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxCommRate As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''fteCommRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fteCommRate As Global.AjaxControlToolkit.FilteredTextBoxExtender

        '''<summary>
        '''plCalc85 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCalc85 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCalc85 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCalc85 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trDvrDedPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trDvrDedPct As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plDvrDedPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDvrDedPct As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDvrDedPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDvrDedPct As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''fteDvrDedPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fteDvrDedPct As Global.AjaxControlToolkit.FilteredTextBoxExtender

        '''<summary>
        '''trDvrDedResn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trDvrDedResn As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plDvrDedResn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDvrDedResn As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDvrDedResn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDvrDedResn As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plJRCTrailer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plJRCTrailer As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtJRCTrailer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtJRCTrailer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plDriverNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDriverNotes As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDriverNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDriverNotes As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trAccountAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAccountAdmin As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''chkProbDriver control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkProbDriver As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plAdminExempt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAdminExempt As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAdminExempt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAdminExempt As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plBrokerCodeD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBrokerCodeD As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtBrokerCodeD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBrokerCodeD As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plLicenceDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLicenceDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLicenceDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLicenceDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgLicenceDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgLicenceDate As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''calLicenceDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calLicenceDate As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plDrugDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDrugDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDrugDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDrugDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgDrugDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgDrugDate As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''calDrugDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calDrugDate As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plMedicalDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMedicalDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtMedicalDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMedicalDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgMedicalDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgMedicalDate As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''calMedicalDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calMedicalDate As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plInactivateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plInactivateDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtInactivateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInactivateDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgInactivateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgInactivateDate As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''calInactivateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calInactivateDate As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''valInactivateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valInactivateDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxInactivateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxInactivateDate As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plLogBookOS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLogBookOS As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkLogBookOS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLogBookOS As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plTruckInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTruckInsDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTruckInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTruckInsDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgTruckInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgTruckInsDate As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''calTruckInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calTruckInsDate As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plTrailerInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTrailerInsDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTrailerInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTrailerInsDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgTrailerInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgTrailerInsDate As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''calTrailerInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calTrailerInsDate As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plRegRenewDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRegRenewDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRegRenewDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRegRenewDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgRegRenewDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgRegRenewDate As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''calRegRenewDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calRegRenewDate As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plNewLeaseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNewLeaseDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtNewLeaseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNewLeaseDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgNewLeaseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgNewLeaseDate As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''calNewLeaseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calNewLeaseDate As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plMoMaint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMoMaint As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtMoMaint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMoMaint As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypMoMaint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypMoMaint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''calMoMaint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calMoMaint As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plDotInspec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDotInspec As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDotInspec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDotInspec As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypDotInspec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypDotInspec As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''calDotInspec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calDotInspec As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plTrailerMaint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTrailerMaint As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTrailerMaint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTrailerMaint As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypTrailerMaint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypTrailerMaint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''calTrailerMaint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calTrailerMaint As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plRegRenew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRegRenew As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRegRenew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRegRenew As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypRegRenew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypRegRenew As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''calRegRenew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calRegRenew As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plOccIns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOccIns As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtOccIns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOccIns As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypOccIns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypOccIns As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''calOccIns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calOccIns As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plNtlIns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNtlIns As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtNtlIns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNtlIns As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypNtlIns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypNtlIns As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''calNtlIns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calNtlIns As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plPhysDmg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPhysDmg As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPhysDmg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhysDmg As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypPhysDmg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypPhysDmg As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''calPhysDmg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calPhysDmg As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plSeaLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSeaLink As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSeaLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeaLink As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypSeaLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypSeaLink As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''calSeaLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calSeaLink As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plAnnIns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAnnIns As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAnnIns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAnnIns As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypAnnIns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypAnnIns As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''calAnnIns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calAnnIns As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''ctlSalesPersonIOs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlSalesPersonIOs As Global.DotNetNuke.UI.UserControls.DualListControl

        '''<summary>
        '''btnUpdateIOs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateIOs As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''trTermination control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trTermination As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''chkTerminated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkTerminated As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDriverCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDriverName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDriverName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plTerm_Staff control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTerm_Staff As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTerm_Staff control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTerm_Staff As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plTerm_Date control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTerm_Date As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTerm_Date control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTerm_Date As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypTerm_Date control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypTerm_Date As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''calTerm_Date control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calTerm_Date As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''valTerm_Date control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTerm_Date As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxTerm_Date control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxTerm_Date As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''valTerm_Date1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTerm_Date1 As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''vlxTerm_Date1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxTerm_Date1 As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plTerm_Reason control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTerm_Reason As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTerm_Reason control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTerm_Reason As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valTerm_Reason control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTerm_Reason As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxTerm_Reason control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxTerm_Reason As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''cmdUnterminate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUnterminate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''divPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPopup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlAudit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAudit As Global.DotNetNuke.UI.UserControls.ModuleAuditControl

        '''<summary>
        '''ctlTracking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTracking As Global.DotNetNuke.UI.UserControls.URLTrackingControl

        '''<summary>
        '''plAddressLine2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddressLine2 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plAddressLine3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddressLine3 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAddressLine3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddressLine3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plState As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plZipCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plLoadType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLoadType As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLoadType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLoadType As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCalc87 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCalc87 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCalc87 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCalc87 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plViewOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plViewOrder As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtViewOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtViewOrder As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
