//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bhattji.Modules.SalesReps
{
	public partial class ViewZipCodes
	{
		protected System.Web.UI.HtmlControls.HtmlTable tblManageZipCodes;
		protected System.Web.UI.HtmlControls.HtmlTableRow trAddZipCode;
		protected System.Web.UI.HtmlControls.HtmlTable tblAddZipCode;
		protected System.Web.UI.WebControls.Label lblItemId;
		protected DotNetNuke.UI.UserControls.LabelControl plZipCode;
		protected System.Web.UI.WebControls.TextBox txtZipCode;
		protected System.Web.UI.WebControls.ImageButton imbSearchZipCode;
		protected DotNetNuke.UI.UserControls.LabelControl plArea;
		protected System.Web.UI.WebControls.TextBox txtArea;
		protected System.Web.UI.WebControls.ImageButton imbSearchArea;
		protected DotNetNuke.UI.UserControls.LabelControl plCity;
		protected System.Web.UI.WebControls.TextBox txtCity;
		protected System.Web.UI.WebControls.ImageButton imbSearchCity;
		protected DotNetNuke.UI.UserControls.LabelControl plStateCode;
		protected System.Web.UI.WebControls.TextBox txtState;
		protected System.Web.UI.WebControls.TextBox txtStateCode;
		protected DotNetNuke.UI.UserControls.LabelControl plSearchZipCode;
		protected System.Web.UI.WebControls.DropDownList ddlZipCodes;
		protected System.Web.UI.HtmlControls.HtmlTableCell tdAdd;
		protected System.Web.UI.WebControls.ImageButton imbAdd;
		protected System.Web.UI.WebControls.LinkButton cmdAdd;
		protected System.Web.UI.HtmlControls.HtmlTableCell tdUpdate;
		protected System.Web.UI.WebControls.ImageButton imbUpdate;
		protected System.Web.UI.WebControls.LinkButton cmdUpdate;
		protected System.Web.UI.WebControls.ImageButton imbCancel;
		protected System.Web.UI.WebControls.LinkButton cmdCancel;
		protected System.Web.UI.HtmlControls.HtmlTableRow trManageZipCodes;
		protected System.Web.UI.WebControls.GridView gdvZipCodes;
		protected System.Web.UI.WebControls.ObjectDataSource odsZipCodes;
		protected System.Web.UI.HtmlControls.HtmlGenericControl divClose;
		protected System.Web.UI.WebControls.HyperLink hypImgClose;
		protected System.Web.UI.WebControls.HyperLink hypClose;
		protected System.Web.UI.HtmlControls.HtmlTableCell tdMsg;
	}
}
