//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bhattji.Modules.SalesReps
{
	public partial class ViewCategories
	{
		protected System.Web.UI.HtmlControls.HtmlTable tblManageCategories;
		protected System.Web.UI.HtmlControls.HtmlTableRow trManageCategories;
		protected System.Web.UI.WebControls.GridView gdvCategories;
		protected System.Web.UI.WebControls.ObjectDataSource odsCategories;
		protected System.Web.UI.HtmlControls.HtmlGenericControl divClose;
		protected System.Web.UI.WebControls.HyperLink hypImgClose;
		protected System.Web.UI.WebControls.HyperLink hypClose;
		protected System.Web.UI.HtmlControls.HtmlTableRow trAddCategory;
		protected System.Web.UI.WebControls.Label lblItemId;
		protected DotNetNuke.UI.UserControls.LabelControl plCategory;
		protected System.Web.UI.WebControls.TextBox txtCategory;
		protected System.Web.UI.WebControls.RequiredFieldValidator valCategory;
		protected DotNetNuke.UI.UserControls.LabelControl plViewOrder;
		protected System.Web.UI.WebControls.TextBox txtViewOrder;
		protected System.Web.UI.HtmlControls.HtmlTableCell tdAdd;
		protected System.Web.UI.WebControls.ImageButton imbAdd;
		protected System.Web.UI.WebControls.LinkButton cmdAdd;
		protected System.Web.UI.HtmlControls.HtmlTableCell tdUpdate;
		protected System.Web.UI.WebControls.ImageButton imbUpdate;
		protected System.Web.UI.WebControls.LinkButton cmdUpdate;
		protected System.Web.UI.WebControls.ImageButton imbCancel;
		protected System.Web.UI.WebControls.LinkButton cmdCancel;
		protected System.Web.UI.HtmlControls.HtmlTableCell tdDelete;
		protected System.Web.UI.WebControls.ImageButton imbDelete;
		protected System.Web.UI.WebControls.LinkButton cmdDelete;
	}
}
