//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bhattji.Modules.SalesReps
{
	public partial class Ratings
	{
		protected System.Web.UI.WebControls.Label lblRatings;
		protected System.Web.UI.WebControls.RadioButtonList rblRatings;
		protected System.Web.UI.HtmlControls.HtmlTableCell tdUpdate;
		protected System.Web.UI.WebControls.ImageButton imbUpdate;
		protected System.Web.UI.WebControls.LinkButton cmdUpdate;
		protected System.Web.UI.HtmlControls.HtmlTableCell tdCancel;
		protected System.Web.UI.WebControls.ImageButton imbCancel;
		protected System.Web.UI.WebControls.LinkButton cmdCancel;
		protected System.Web.UI.HtmlControls.HtmlTableCell tdClose;
		protected System.Web.UI.WebControls.ImageButton imbClose;
		protected System.Web.UI.WebControls.LinkButton cmdClose;
	}
}
