//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bhattji.Modules.SalesReps {
    
    public partial class ViewList {
        protected System.Web.UI.HtmlControls.HtmlTable tblSearch;
        protected System.Web.UI.WebControls.RadioButtonList rblSearchOn;
        protected System.Web.UI.WebControls.RadioButtonList rblSearchType;
        protected System.Web.UI.WebControls.Label plFromDate;
        protected System.Web.UI.WebControls.TextBox txtFrom;
        protected System.Web.UI.WebControls.Image imgFrom;
        protected AjaxControlToolkit.CalendarExtender calFrom;
        protected System.Web.UI.WebControls.Label plToDate;
        protected System.Web.UI.WebControls.TextBox txtTo;
        protected System.Web.UI.WebControls.Image imgTo;
        protected AjaxControlToolkit.CalendarExtender calTo;
        protected System.Web.UI.WebControls.DropDownList ddlCategories;
        protected System.Web.UI.WebControls.HyperLink hypEditCategory;
        protected System.Web.UI.WebControls.TextBox txtSearch;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.WebControls.GridView gdvViewList;
        protected System.Web.UI.WebControls.ObjectDataSource odsSalesReps;
    }
}
