'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhattji.Modules.BkrSalesPersons

    Partial Public Class EditItem

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''valValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''trUpdateRedirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trUpdateRedirection As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ddlUpdateRedirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlUpdateRedirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdAdd As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imbAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbAdd As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdUpdate As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imbUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbUpdate As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbCancel As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdDelete As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imbDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbDelete As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdPrint As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''hypImgPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypImgPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''plDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDriverCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDriverCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDriverCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''cvDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvDriverCode As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''actDriverCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents actDriverCode As Global.AjaxControlToolkit.FilteredTextBoxExtender

        '''<summary>
        '''plBrokerCodeD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBrokerCodeD As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtBrokerCodeD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBrokerCodeD As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnBrokerSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBrokerSearch As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''valBrokerCodeD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valBrokerCodeD As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''cvBrokerCodeD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvBrokerCodeD As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''ddlBrokerCodeD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBrokerCodeD As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''reqBrokerCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents reqBrokerCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plDFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDFirstName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plDLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDLastName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plOfficeOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOfficeOwner As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlOfficeOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlOfficeOwner As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''imgStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgStatus As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''plDriverName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDriverName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDriverName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDriverName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plAddressLine1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddressLine1 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAddressLine1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddressLine1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAddressLine2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddressLine2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCity As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtState As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtZipCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCountryCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCountryCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCountryCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCountryCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plPhoneNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPhoneNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPhoneNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhoneNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plExt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plExt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtExt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExt As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''meePhoneNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents meePhoneNo As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''plFaxNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFaxNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtFaxNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFaxNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''meeFaxNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents meeFaxNo As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''plCellPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCellPhone As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCellPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCellPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plPager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPager As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''meeCellPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents meeCellPhone As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''txtPager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPager As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''meePager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents meePager As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''plEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailAddress As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tdLastLoadID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdLastLoadID As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''plLastLoadID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastLoadID As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plLastLoad control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastLoad As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastLoadID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastLoadID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLastLoad control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastLoad As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgLastLoad control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgLastLoad As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''calLastLoad control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calLastLoad As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plLastLoadDeliv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastLoadDeliv As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastLoadDeliv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastLoadDeliv As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgLastLoadDeliv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgLastLoadDeliv As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''calLastLoadDeliv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calLastLoadDeliv As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plLastPU control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastPU As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plLastDP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastDP As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastPU control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastPU As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLastDP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastDP As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plLastTrailerUsed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLastTrailerUsed As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLastTrailerUsed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastTrailerUsed As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trAccountNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAccountNo As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAccountNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAccountNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAccountNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAccountNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CustomValidator2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CustomValidator2 As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''plCommRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCommRate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCommRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCommRate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCalc85 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCalc85 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCalc85 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCalc85 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plJRCTrailer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plJRCTrailer As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtJRCTrailer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtJRCTrailer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plDriverNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDriverNotes As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDriverNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDriverNotes As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trAccountAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAccountAdmin As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''plAdminExempt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAdminExempt As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAdminExempt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAdminExempt As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plDrugDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDrugDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plTruckInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTruckInsDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDrugDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDrugDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalendarDrugDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalendarDrugDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''txtTruckInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTruckInsDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalendarTruckInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalendarTruckInsDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''plLicenceDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLicenceDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plTrailerInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTrailerInsDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLicenceDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLicenceDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalendarLicenceDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalendarLicenceDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''txtTrailerInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTrailerInsDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalendarTrailerInsDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalendarTrailerInsDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''plRegRenewDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRegRenewDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plNewLeaseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNewLeaseDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRegRenewDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRegRenewDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalendarRegRenewDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalendarRegRenewDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''txtNewLeaseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNewLeaseDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalendarNewLeaseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalendarNewLeaseDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''plMedicalDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMedicalDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plLogBookOS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLogBookOS As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtMedicalDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMedicalDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalendarMedicalDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalendarMedicalDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''chkLogBookOS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLogBookOS As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ctlSalesPersonIOs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlSalesPersonIOs As Global.DotNetNuke.UI.UserControls.DualListControl

        '''<summary>
        '''btnUpdateIOs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateIOs As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''divPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPopup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlAudit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAudit As Global.DotNetNuke.UI.UserControls.ModuleAuditControl

        '''<summary>
        '''ctlTracking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTracking As Global.DotNetNuke.UI.UserControls.URLTrackingControl

        '''<summary>
        '''plAddressLine2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddressLine2 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plAddressLine3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddressLine3 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAddressLine3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddressLine3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plState As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plZipCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plLoadType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLoadType As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLoadType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLoadType As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSafetyAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSafetyAuth As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSafetyAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSafetyAuth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSafetyNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSafetyNotes As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSafetyNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSafetyNotes As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCalc87 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCalc87 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCalc87 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCalc87 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plViewOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plViewOrder As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtViewOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtViewOrder As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
