'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhattji.Modules.BkrSalesPersons

    Partial Public Class ViewList

        '''<summary>
        '''lblBroker control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBroker As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBrokerCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBrokerCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnBrokerSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBrokerSearch As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lblBokerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBokerName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlBrokerCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBrokerCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rblSearchOn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSearchOn As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''rblSearchType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSearchType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFromDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFrom As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgFrom As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''calFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calFrom As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plToDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgTo As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''calTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calTo As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''plStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblStatus As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plJRCIOfficeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plJRCIOfficeCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlJRCIOfficeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlJRCIOfficeCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''gdvViewList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvViewList As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''odsSalesPersons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsSalesPersons As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
