'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace bhattji.Modules.SalesReps
    Partial Public Class Details
        Protected WithEvents plRepNo As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtRepNo As System.Web.UI.WebControls.Label
        Protected WithEvents plRepName As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtRepName As System.Web.UI.WebControls.Label
        Protected WithEvents plRepRate As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtRepRate As System.Web.UI.WebControls.Label
        Protected WithEvents plRepDollar As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtRepDollar As System.Web.UI.WebControls.Label
        Protected WithEvents divButtons As System.Web.UI.HtmlControls.HtmlGenericControl
        Protected WithEvents tdEdit As System.Web.UI.HtmlControls.HtmlTableCell
        Protected WithEvents hypImgEdit As System.Web.UI.WebControls.HyperLink
        Protected WithEvents hypEdit As System.Web.UI.WebControls.HyperLink
        Protected WithEvents hypImgClose As System.Web.UI.WebControls.HyperLink
        Protected WithEvents hypClose As System.Web.UI.WebControls.HyperLink
        Protected WithEvents hypImgPrint As System.Web.UI.WebControls.HyperLink
        Protected WithEvents hypPrint As System.Web.UI.WebControls.HyperLink
        Protected WithEvents ctlAudit As DotNetNuke.UI.UserControls.ModuleAuditControl
        Protected WithEvents ctlTracking As DotNetNuke.UI.UserControls.URLTrackingControl
        Protected WithEvents plViewOrder As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtViewOrder As System.Web.UI.WebControls.Label
    End Class
End Namespace
