'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhattji.Modules.Customers

    Partial Public Class EditItem

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''valValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''trUpdateRedirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trUpdateRedirection As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''ddlUpdateRedirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlUpdateRedirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdAdd As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imbAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbAdd As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdUpdate As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imbUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbUpdate As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbCancel As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdDelete As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imbDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbDelete As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdPrint As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''hypImgPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypImgPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''plCustomerNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCustomerNumber As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plCustomerStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCustomerStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plCStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCustomerNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomerNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvCustomerNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvCustomerNumber As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''vlxCustomerNumber0 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxCustomerNumber0 As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''actCustomerNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents actCustomerNumber As Global.AjaxControlToolkit.FilteredTextBoxExtender

        '''<summary>
        '''valCustomerNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCustomerNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxCustomerNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxCustomerNumber As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''ddlCustomerStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCustomerStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlCStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''jrcmaintable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents jrcmaintable As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plCustomerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCustomerName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCustomerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomerName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valCustomerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCustomerName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vlxCustomerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vlxCustomerName As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''plAddressLine1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddressLine1 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAddressLine1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddressLine1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAddressLine2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddressLine2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCity As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlStateCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStateCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtZipCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valState As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plContactCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plContactCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtContactCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContactCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plPhoneNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPhoneNumber As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPhoneNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhoneNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''meePhoneNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents meePhoneNumber As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''plExt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plExt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtExt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExt As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plFaxNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFaxNumber As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtFaxNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFaxNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''meeFaxNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents meeFaxNumber As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''plRepNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRepNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlRepNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRepNo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plRepName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRepName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRepName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRepName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plRepPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRepPct As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRepPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRepPct As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''fteRepPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fteRepPct As Global.AjaxControlToolkit.FilteredTextBoxExtender

        '''<summary>
        '''plRepDlr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRepDlr As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRepDlr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRepDlr As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''fteRepDlr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fteRepDlr As Global.AjaxControlToolkit.FilteredTextBoxExtender

        '''<summary>
        '''plCowner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCowner As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlCowner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCowner As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plCorpUpd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCorpUpd As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCorpUpd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCorpUpd As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalendarCorpUpd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalendarCorpUpd As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''plWhoDoneIT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plWhoDoneIT As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtWhoDoneIT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWhoDoneIT As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plDivision control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDivision As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDivision control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDivision As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plBillingInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBillingInfo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtBillingInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBillingInfo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plGSMStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plGSMStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtGSMStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtGSMStatus As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPopup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlAudit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAudit As Global.DotNetNuke.UI.UserControls.ModuleAuditControl

        '''<summary>
        '''ctlTracking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTracking As Global.DotNetNuke.UI.UserControls.URLTrackingControl

        '''<summary>
        '''plAddressLine2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddressLine2 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plAddressLine3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddressLine3 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAddressLine3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddressLine3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plState As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plZipCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''plFavor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFavor As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtFavor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFavor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSortSeq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortSeq As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSortSeq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSortSeq As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plOldCustNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOldCustNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtOldCustNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOldCustNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plMCNO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMCNO As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtMCNO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMCNO As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plViewOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plViewOrder As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtViewOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtViewOrder As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
