'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace bhattji.Modules.InterOffices
    Partial Public Class ViewWords
        Protected WithEvents rblSearchOn As System.Web.UI.WebControls.RadioButtonList
        Protected WithEvents rblSearchType As System.Web.UI.WebControls.RadioButtonList
        Protected WithEvents plFromDate As System.Web.UI.WebControls.Label
        Protected WithEvents txtFrom As System.Web.UI.WebControls.TextBox
        Protected WithEvents hypCalandarFromDate As System.Web.UI.WebControls.HyperLink
        Protected WithEvents plToDate As System.Web.UI.WebControls.Label
        Protected WithEvents txtTo As System.Web.UI.WebControls.TextBox
        Protected WithEvents hypCalandarToDate As System.Web.UI.WebControls.HyperLink
        Protected WithEvents txtSearch As System.Web.UI.WebControls.TextBox
        Protected WithEvents btnSearch As System.Web.UI.WebControls.Button
        Protected WithEvents gdvViewList As System.Web.UI.WebControls.GridView
        Protected WithEvents odsInterOffices As System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
