'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhattji.Modules.LoadSheets

    Partial Public Class EditLoadDrops

        '''<summary>
        '''tblManageLoadDrops control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblManageLoadDrops As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''trAddLoadDrop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAddLoadDrop As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''trManageLoadDrops control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trManageLoadDrops As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lnkAddLoadDrop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkAddLoadDrop As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tblAddLoadDrop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAddLoadDrop As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plDPCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDPCity As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDPCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDPCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''aceDPCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents aceDPCity As Global.AjaxControlToolkit.AutoCompleteExtender

        '''<summary>
        '''plDPState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDPState As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDPState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDPState As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imbSearchCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbSearchCity As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''plZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plZipCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtZipCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imbSearchZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbSearchZipCode As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''plDPDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDPDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDPDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDPDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''actDPDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents actDPDate As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''imgDPDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgDPDate As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''plSearchZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchZipCode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlZipCodes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlZipCodes As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''secAdditionalInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents secAdditionalInfo As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''trAdditionalInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAdditionalInfo As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plDPName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDPName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDPName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDPName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plDPContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDPContact As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDPContact control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDPContact As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plDPPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDPPhone As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDPPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDPPhone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plDPAddr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDPAddr As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDPAddr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDPAddr As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSeq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSeq As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSeq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeq As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''meeDPPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents meeDPPhone As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''plJobno control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plJobno As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtJobno control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtJobno As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plBillOLay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBillOLay As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlBillOLay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBillOLay As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plBOLSeq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBOLSeq As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtBOLSeq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBOLSeq As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plStime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStime As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtStime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plEtime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEtime As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEtime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEtime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblItemId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblItemId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''imbAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbAdd As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbCancel As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''divLoadDPs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divLoadDPs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''gdvLoadDrops control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvLoadDrops As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''hypImgClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypImgClose As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypClose As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''odsLoadDrops control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsLoadDrops As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''UpdateProgress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
    End Class
End Namespace
