'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhattji.Modules.LoadSheets

    Partial Public Class EditPUDrops

        '''<summary>
        '''uprEditPUDrops control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents uprEditPUDrops As Global.System.Web.UI.UpdateProgress

        '''<summary>
        '''lnbHome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbHome As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbHome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbHome As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbUpdateLoadsheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbUpdateLoadsheet As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbUpdateLoadsheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbUpdateLoadsheet As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbUpdateAccounting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbUpdateAccounting As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbUpdateAccounting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbUpdateAccounting As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbUpdateAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbUpdateAddNew As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbUpdateAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbUpdateAddNew As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbUpdateToList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbUpdateToList As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbUpdateToList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbUpdateToList As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbPrint As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbPrint As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbPrintConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbPrintConfirm As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbPrintConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbPrintConfirm As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lblLoadId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLoadId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCustomer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomer As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDriver control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDriver As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCustPO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustPO As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''phtLoadPUs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phtLoadPUs As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''phtLoadDrops control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phtLoadDrops As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''hypBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypBack As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypBack1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypBack1 As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
