'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhattji.Modules.LoadSheets

    Partial Public Class rptLoadConfirm

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReportHeading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportHeading As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdEdit As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''hypImgEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypImgEdit As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypEdit As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypImgClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypImgClose As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypClose As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypImgPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypImgPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypPrint As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypImgPdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypImgPdf As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypPdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypPdf As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''imbEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbEmail As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbEmail As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbEmailPdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbEmailPdf As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbEmailPdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbEmailPdf As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ctlAudit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAudit As Global.DotNetNuke.UI.UserControls.ModuleAuditControl

        '''<summary>
        '''lblOOMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOOMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tblLoadConfrm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblLoadConfrm As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''tblDriverPayables control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblDriverPayables As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblJRCIOfficeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblJRCIOfficeCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Table8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table8 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''Table1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblLoadId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLoadId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLoadDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLoadDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Table7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table7 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblLoadNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLoadNotes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Table2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblCarrierName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCarrierName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Table3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table3 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblJRCarrier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblJRCarrier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTrailerNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTrailerNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTrailerDue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTrailerDue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTrailerType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTrailerType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Table4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table4 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblPhNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPhNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCellPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCellPhone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFaxNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFaxNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Table9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table9 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblBWords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBWords As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Table5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table5 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblTarpMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTarpMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Table6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table6 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblDRTotDue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDRTotDue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gdvLoadPUs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvLoadPUs As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''odsLoadPUs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsLoadPUs As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''gdvLoadDrops control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvLoadDrops As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''odsLoadDrops control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsLoadDrops As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
