'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhattji.Modules.LoadSheets

    Partial Public Class rvContainer

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''tblSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSearch As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblCustomer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomer As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCustomerNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomerNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnCustomerSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCustomerSearch As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lblCustomerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomerName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlCustomerNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCustomerNumber As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''LoadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LoadStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlLoadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLoadStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''divReportTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divReportTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblReportTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlReportTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlReportTitle As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rblSearchOn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSearchOn As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plSearchDriver control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchDriver As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSearchDriver control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearchDriver As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlDriverStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDriverStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''rblSearchType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSearchType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFromDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFrom As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypCalandarFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypCalandarFromDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''plToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plToDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypCalandarToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypCalandarToDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''imbRefresh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbRefresh As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''tdNoOfItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdNoOfItems As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''plNoOfItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNoOfItems As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtNoOfItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNoOfItems As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plJRCIOfficeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plJRCIOfficeCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlJRCIOfficeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlJRCIOfficeCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plSort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSort As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlSort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSort As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkSortDesc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSortDesc As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imbEmailPdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbEmailPdf As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbEmailPdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbEmailPdf As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbPrintReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbPrintReport As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''imbPrintSelection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbPrintSelection As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''hypLoadList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypLoadList As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hyprvXmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hyprvXmission As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''ReportViewer1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportViewer1 As Global.Microsoft.Reporting.WebForms.ReportViewer
    End Class
End Namespace
