'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhattji.Modules.LoadSheets

    Partial Public Class ViewReport

        '''<summary>
        '''rblSearchOn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSearchOn As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''rblSearchType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSearchType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFromDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plToDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plJRCIOfficeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plJRCIOfficeCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LoadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LoadStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFrom As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgFrom As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''calFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calFrom As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''txtTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgTo As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''calTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calTo As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''ddlJRCIOfficeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlJRCIOfficeCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlLoadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLoadStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''gdvViewReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvViewReport As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''odsLoadSheets control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsLoadSheets As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''hypSysInquiry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypSysInquiry As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypDrvCerti control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypDrvCerti As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypReport1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypReport1 As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypReport2Driver control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypReport2Driver As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypReport2Broker control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypReport2Broker As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypLoadStatusReview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypLoadStatusReview As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypDriverStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypDriverStatus As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypXmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypXmission As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypContainer As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
