'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bhattji.Modules.LoadSheets

    Partial Public Class Xmission

        '''<summary>
        '''rblSearchOn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSearchOn As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''chkCodOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCodOnly As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkMissingCodOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkMissingCodOnly As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rblSearchType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSearchType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFromDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFrom As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypCalandarFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypCalandarFromDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''plToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plToDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypCalandarToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypCalandarToDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''plJRCIOfficeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plJRCIOfficeCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlJRCIOfficeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlJRCIOfficeCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''gdvViewList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gdvViewList As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnXmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnXmission As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''hypXmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypXmission As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''ddlXmissionFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlXmissionFile As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tdUnXmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdUnXmission As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''imgUnXmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgUnXmission As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbUnXmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbUnXmission As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tdXmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdXmission As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''chkRedirect2Report control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRedirect2Report As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''imbSelectAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbSelectAll As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbSelectAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbSelectAll As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbUnSelectAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbUnSelectAll As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbUnSelectAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbUnSelectAll As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbSave As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbSave As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbCancel As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imbXmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imbXmission As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lnbXmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnbXmission As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''odsLoadSheets control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsLoadSheets As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''hypReport1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypReport1 As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypReport2Driver control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypReport2Driver As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypReport2Broker control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypReport2Broker As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypReport3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypReport3 As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hypDriverStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypDriverStatus As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
